Setup GitHub Actions for CI
jobsgowhere/jobsgowhere pull request #39
Opened 2020-04-08 17:28 UTC by subhransu

Setup GitHub Actions to Trigger build for PR and when pushed to master. 

At this moment this PR sets up:

* Necessary packages
* Makes a docker build 
* Tags the docker build
* And pushes to a private docker repository 

## Further work is still remaining to host te docker build once this PR is merged.

2020-04-08 17:33 UTC, subhransu commented
Build fails as the secrets are not passed to PRs created from a fork.
Successful build can be found here: https://github.com/subhransu/jobsgowhere/runs/571512423

2020-04-10 02:53 UTC, kajalsinha commented
https://stackoverflow.com/questions/30970591/automatic-docker-login-within-a-bash-script/30971862 <-- this might help to fix docker login issue @subhransu

2020-04-10 09:47 UTC, subhransu commented
@kajalsinha I am using the same [here](https://github.com/jobsgowhere/jobsgowhere/pull/39/files#diff-90829e76e906f1c73140c7ded7e1b268R27)

but the secrets won't be passed if it is a PR from a forked repo. 

This workflow is working properly so we just need to merge the PR and then it will work once it's merged.

2020-04-11 02:45 UTC, ivanfoong requested changes

2020-04-11 02:45 UTC, ivanfoong commented on Makefile
> +docker-pus:
`docker-pus` typo?

2020-04-11 02:45 UTC, ivanfoong commented on Makefile
> +	npm install webpack-dev-server rimraf webpack react-scripts -g
is this Github Action specific? or its required by the react build process? If required by build process, should we just add it into frontend `package.json`

2020-04-12 15:19 UTC, subhransu commented
Closing this PR as created a branch on this repo and sent #48 
This addresses the changes requested on this PR as well.

2020-04-12 15:19 UTC, closed without merging